name: finalproject
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: any
  firebase_core: ^2.15.0
  intl: any
  carousel_slider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/components/images/batteryfull24px.png
    - assets/components/images/glass.png
    - assets/components/images/like-icon.png
    - assets/components/images/frame-1171274890.png
    - assets/components/images/vuesax-linear-category.png
    - assets/components/images/icon-plus.png
    - assets/components/images/like-icon-k57.png
    - assets/components/images/nearme24px.png
    - assets/components/images/icon-plus-Wrm.png
    - assets/components/images/vuesax-bold-home-2.png
    - assets/components/images/frame-1171274870.png
    - assets/components/images/filter.png
    - assets/components/images/frame-1171274892.png
    - assets/components/images/vuesax-linear-shopping-cart.png
    - assets/components/images/frame-32.png
    - assets/components/images/vuesax-bold-heart.png
    - assets/components/images/.png
    - assets/components/images/iconly-j4d.png
    - assets/components/images/iconly.png
    - assets/components/images/back.png
    - assets/components/images/vuesax-linear-arrow-down.png
    - assets/components/images/group-3244.png
    - assets/components/images/icon-minus.png
    - assets/components/images/status-bar.png
    - assets/components/images/menu.png
    - assets/components/images/image-43.png
    - assets/components/images/frame-1171274869.png
    - assets/components/images/vuesax-linear-heart.png
    - assets/components/images/star.png
    - assets/components/images/mask-group.png
    - assets/components/images/vuesax-linear-arrow-down-epq.png
    - assets/components/images/like-icon-RFo.png
    - assets/components/images/icon-plus-Ke1.png
    - assets/components/images/icon-plus-aDo.png
    - assets/components/images/menu-hJR.png
    - assets/components/images/frame-1171274973-9TF.png
    - assets/components/images/iconography-caesarzkn.png
    - assets/components/images/image-58.png
    - assets/components/images/mask-group-9so.png
    - assets/components/images/vuesax-linear-shopping-cart-Ad7.png
    - assets/components/images/status-bar-p8y.png
    - assets/components/images/frame-1171274974.png
    - assets/components/images/rss-feed.png
    - assets/components/images/frame-1171274891.png
    - assets/components/images/icon-minus-u8u.png
    - assets/components/images/bottom-navigation.png
    - assets/components/images/equalizer24px.png
    - assets/components/images/vuesax-linear-profile.png
    - assets/components/images/frame-1171274974-88h.png
    - assets/components/images/frame-32-jCM.png
    - assets/components/images/vuesax-linear-heart-MQ5.png
    - assets/components/images/frame-1171274869-8PT.png
    - assets/components/images/vuesax-linear-category-SiD.png
    - assets/components/images/frame-1171274973.png
    - assets/components/images/frame.png
    - assets/components/images/chevron-bar-up-n8H.png
    - assets/components/images/menu-Ke1.png
    - assets/components/images/status-bar-pKs.png
    - assets/components/images/image-56.png
    - assets/components/images/frame-1171274889.png
    - assets/components/images/back-aqP.png
    - assets/components/images/chevron-bar-down.png
    - assets/components/images/chevron-bar-up-PGM.png
    - assets/components/images/menu-btn-user.png
    - assets/components/images/icon-minus-eAu.png
    - assets/components/images/iconly-light-filter.png
    - assets/components/images/star-CFb.png
    - assets/components/images/frame-1171274974-wiy.png
    - assets/components/images/chevron-bar-down-5ms.png
    - assets/components/images/frame-1171274974-FTP.png
    - assets/components/images/frame-1171274974-NRX.png
    - assets/components/images/chevron-bar-up-7R3.png
    - assets/components/images/like-icon-qvh.png
    - assets/components/images/frame-1171274973-cC1.png
    - assets/components/images/frame-1171274973-xFs.png
    - assets/components/images/chevron-bar-down-Nkq.png
    - assets/components/images/-Y6u.png
    - assets/components/images/frame-1171274974-74m.png
    - assets/components/images/chevron-bar-down-2Bj.png
    - assets/components/images/chevron-bar-down-v3T.png
    - assets/components/images/chevron-bar-down-XhT.png
    - assets/components/images/chevron-bar-up-SZX.png
    - assets/components/images/visapict.png
    - assets/components/images/chevron-bar-up-wkM.png
    - assets/components/images/icon-minus-4a5.png
    - assets/components/images/iconography-caesarzkn-AAD.png
    - assets/components/images/image-48.png
    - assets/components/images/frame-1171274973-Gi5.png
    - assets/components/images/image-43-5n9.png
    - assets/components/images/image-43-uXX.png
    - assets/components/images/image-58-bg.png
    - assets/components/images/visapict-azM.png
    - assets/components/images/image-48-Kww.png
    - assets/components/images/image-43-bg.png
    - assets/components/images/image-57-bg.png
    - assets/components/images/image-48-WjT.png
    - assets/components/images/image-43-bg-pk9.png
    - assets/components/images/image-43-VXX.png
    - assets/components/images/image-43-bg-2XT.png
    - assets/components/images/image-48-Pv9.png
    - assets/components/images/image-43-bg-wAy.png
    - assets/components/images/image-43-bg-jLm.png
    - assets/components/images/image-62.png
    - assets/components/images/image-43-BTX.png
    - assets/components/images/image-43-bg-HmT.png
    - assets/components/images/image-57-bg-m8D.png
    - assets/components/images/image-43-bg-6RP.png
    - assets/components/images/chevron-bar-up.png
    - assets/components/images/menu-9cu.png
    - assets/components/images/image-54-bg.png
    - assets/components/images/iconly-QG1.png
    - assets/components/images/frame-1171274974-82D.png
    - assets/components/images/status-bar-11T.png
    - assets/components/images/image-55.png
    - assets/components/images/property-1default.png
    - assets/components/images/image-55-92H.png
    - assets/components/images/image-54-bg-Gsb.png
    - assets/components/images/image-62-q8m.png
    - assets/components/images/image-43-7Vb.png
    - assets/components/images/image-43-Vny.png
    - assets/components/images/image-56-bg.png
    - assets/components/images/image-61.png
    - assets/components/images/filter-Bbo.png
    - assets/components/images/iconography-caesarzkn-YUH.png
    - assets/components/images/iconography-caesarzkn-DKX.png
    - assets/components/images/image-59.png
    - assets/components/images/image-60-bg.png
    - assets/components/images/image-59-bg.png
    - assets/components/images/iconography-caesarzkn-ZHb.png
    - assets/components/images/frame-1171274978.png
    - assets/pages/images/image-43-KLu.png
    - assets/pages/images/image-46.png
    - assets/pages/images/search-button.png
    - assets/pages/images/property-1default-mL5.png
    - assets/components/images/iconography-caesarzkn-Tk5.png
    - assets/pages/images/property-1default-FQ5.png
    - assets/components/images/image-60-bg-Ytq.png
    - assets/components/images/image-61-bg.png
    - assets/pages/images/iconography-caesarzkn-WdP.png
    - assets/pages/images/frame-1171274894.png
    - assets/pages/images/iconography-caesarzkn-JLH.png
    - assets/pages/images/iconography-caesarzkn-kkH.png
    - assets/pages/images/line-2.png
    - assets/pages/images/iconography-caesarzkn-Dih.png
    - assets/pages/images/iconography-caesarzkn-sku.png
    - assets/pages/images/iconography-caesarzkn-qVB.png
    - assets/pages/images/iconography-caesarzkn-pGH.png
    - assets/pages/images/menu-btn-user-TFX.png
    - assets/pages/images/iconography-caesarzkn-5VB.png
    - assets/pages/images/iconography-caesarzkn-pJD.png
    - assets/pages/images/iconography-caesarzkn-kcR.png
    - assets/pages/images/iconography-caesarzkn-Auf.png
    - assets/pages/images/iconography-caesarzkn-d8d.png
    - assets/pages/images/iconography-caesarzkn-PYD.png
    - assets/pages/images/search-button-1d3.png
    - assets/pages/images/menu-btn-user-PHT.png
    - assets/pages/images/iconography-caesarzkn-9Hs.png
    - assets/pages/images/iconography-caesarzkn-WxZ.png
    - assets/pages/images/iconography-caesarzkn-rFj.png
    - assets/pages/images/shopping-cart.png
    - assets/pages/images/iconography-caesarzkn-aDX.png
    - assets/pages/images/frame-1171274910.png
    - assets/pages/images/regularshopping-bag.png
    - assets/pages/images/navigation-chevronright.png
    - assets/pages/images/truck.png
    - assets/pages/images/image-51.png
    - assets/pages/images/frame-1171274910-7R3.png
    - assets/pages/images/iconography-caesarzkn-pLh.png
    - assets/pages/images/frame-1171274910-Bkm.png
    - assets/pages/images/image-51-ob7.png
    - assets/pages/images/iconography-caesarzkn-Ppd.png
    - assets/pages/images/image-53.png
    - assets/pages/images/box.png
    - assets/pages/images/image-53-nbb.png
    - assets/pages/images/image-53-jV3.png
    - assets/pages/images/image-53-L2u.png
    - assets/pages/images/image-53-EgZ.png
    - assets/pages/images/image-53-nFj.png
    - assets/pages/images/image-51-HKo.png
    - assets/pages/images/image-51-C65.png
    - assets/pages/images/notification-sms.png
    - assets/pages/images/image-53-HpD.png
    - assets/pages/images/shopping-cart-b1b.png
    - assets/pages/images/image-51-7Xo.png
    - assets/pages/images/image-51-fgD.png
    - assets/pages/images/image-53-vuX.png
    - assets/pages/images/question-circle-r.png
    - assets/pages/images/frame-1171274910-8zM.png
    - assets/pages/images/action-accountcircle.png
    - assets/pages/images/image-51-yhK.png
    - assets/pages/images/support-star-1.png
    - assets/pages/images/image-51-RBw.png
    - assets/pages/images/action-history.png
    - assets/pages/images/frame-1171274910-SVF.png
    - assets/pages/images/search-button-N3s.png
    - assets/pages/images/navigation-chevronright-ns3.png
    - assets/pages/images/support-like-shapes.png
    - assets/pages/images/finance-sale-badge.png
    - assets/pages/images/shopping-cart-giV.png
    - assets/pages/images/menu-btn-user-2ZX.png
    - assets/pages/images/component.png
    - assets/pages/images/iconography-caesarzkn-iGy.png
    - assets/pages/images/iconography-caesarzkn-qzH.png
    - assets/pages/images/wallet2.png
    - assets/pages/images/frame-1171274910-C4R.png
    - assets/pages/images/action-cardmembership.png
    - assets/pages/images/shopping-cart-Seu.png
    - assets/pages/images/shopping-cart-g7b.png
    - assets/pages/images/action-stars.png
    - assets/pages/images/frame-1171274910-4qF.png
    - assets/pages/images/frame-1171274910-GNV.png
    - assets/pages/images/shopping-cart-z8Z.png
    - assets/pages/images/ian-dooley-d1upkifd04a-unsplash-1.png
    - assets/pages/images/mnz-m1m2ezozvwa-unsplash-1.png
    - assets/pages/images/mnz-m1m2ezozvwa-unsplash-1-j7o.png
    - assets/pages/images/iconography-caesarzkn-77X.png
    - assets/pages/images/mnz-m1m2ezozvwa-unsplash-1-Nvu.png
    - assets/pages/images/mnz-m1m2ezozvwa-unsplash-1-fwX.png
    - assets/pages/images/mnz-m1m2ezozvwa-unsplash-1-exZ.png
    - assets/pages/images/mnz-m1m2ezozvwa-unsplash-1-s9s.png
    - assets/pages/images/chevron-bar-down-CrD.png
    - assets/pages/images/search-button-ax1.png
    - assets/pages/images/frame-1171274973-8DF.png
    - assets/pages/images/search-button-2KB.png
    - assets/pages/images/image-54-bg-ELy.png
    - assets/pages/images/menu-btn-user-iJ5.png
    - assets/pages/images/iconography-caesarzkn-GDF.png
    - assets/pages/images/iconography-caesarzkn-6Jd.png
    - assets/pages/images/iconography-caesarzkn-qWR.png
    - assets/pages/images/icon-minus-Re9.png
    - assets/pages/images/menu-VpD.png
    - assets/pages/images/icon-minus-E7K.png
    - assets/pages/images/icon-plus-YdP.png
    - assets/pages/images/icon-minus-b3P.png
    - assets/pages/images/line-2-c9f.png
    - assets/pages/images/menu-J4q.png
    - assets/pages/images/tab-bar.png
    - assets/pages/images/line-2-zyP.png
    - assets/pages/images/menu-btn-user-gSd.png
    - assets/pages/images/image-43-Uws.png
    - assets/pages/images/menu-8AM.png
    - assets/pages/images/icon-minus-ivV.png
    - assets/pages/images/line-2-XNZ.png
    - assets/pages/images/vuesax-linear-category-ghF.png
    - assets/pages/images/search-button-mKo.png
    - assets/pages/images/menu-kzM.png
    - assets/pages/images/image-43-xim.png
    - assets/pages/images/image-43-o6H.png
    - assets/pages/images/icon-plus-zky.png
    - assets/pages/images/menu-btn-user-qWh.png
    - assets/pages/images/star-fill.png
    - assets/pages/images/search-button-ddb.png
    - assets/pages/images/vector.png
    - assets/pages/images/vuesax-linear-heart-hKo.png
    - assets/pages/images/icon-plus-FZb.png
    - assets/pages/images/vuesax-linear-heart-e2d.png
    - assets/pages/images/icon-plus-SHo.png
    - assets/pages/images/solid-award.png
    - assets/pages/images/line-2-9R3.png
    - assets/pages/images/iconography-caesarzkn-mzR.png
    - assets/pages/images/mask-group-GE5.png
    - assets/pages/images/vuesax-linear-heart-1aq.png
    - assets/pages/images/vuesax-linear-arrow-down-5sP.png
    - assets/pages/images/vuesax-linear-heart-ZVs.png
    - assets/pages/images/vector-BRT.png
    - assets/pages/images/star-fill-aBK.png
    - assets/pages/images/image-43-u93.png
    - assets/pages/images/star-fill-68y.png
    - assets/pages/images/star-fill-H6H.png
    - assets/pages/images/vuesax-linear-heart-8zV.png
    - assets/pages/images/iconography-caesarzkn-MYu.png
    - assets/pages/images/vuesax-linear-heart-SAd.png
    - assets/pages/images/star-fill-iZw.png
    - assets/pages/images/star-fill-NG9.png
    - assets/pages/images/image-43-bg-H2h.png
    - assets/pages/images/image-43-bg-ucd.png
    - assets/pages/images/image-43-bg-Tjw.png
    - assets/pages/images/image-43-bg-Row.png
    - assets/pages/images/image-43-bg-XQd.png
    - assets/pages/images/navigation-arrowforwardios.png
    - assets/pages/images/image-43-bg-ocu.png
    - assets/pages/images/mask-group-Lw3.png
    - assets/pages/images/navigation-arrowforwardios-zpR.png
    - assets/pages/images/navigation-arrowforwardios-sCM.png
    - assets/pages/images/navigation-arrowforwardios-MN1.png
    - assets/pages/images/solid-award-y4M.png
    - assets/pages/images/navigation-arrowforwardios-dff.png
    - assets/pages/images/vector-H3o.png
    - assets/pages/images/vuesax-linear-category-Czd.png
    - assets/pages/images/navigation-arrowforwardios-BhT.png
    - assets/pages/images/iconography-caesarzkn-4Kj.png
    - assets/pages/images/menu-btn-user-ZGu.png
    - assets/pages/images/navigation-arrowforwardios-k7j.png
    - assets/pages/images/image-44.png
    - assets/pages/images/search-button-3Zj.png
    - assets/pages/images/vector-tPb.png
    - assets/pages/images/iconography-caesarzkn-jVj.png
    - assets/pages/images/navigation-arrowforwardios-sbF.png
    - assets/pages/images/vector-B8D.png
    - assets/pages/images/vector-bey.png
    - assets/pages/images/arrow-arrow-down.png
    - assets/pages/images/search-button-uB7.png
    - assets/pages/images/vector-Nsb.png
    - assets/pages/images/vector-dRT.png
    - assets/pages/images/frame-1171274870-at9.png
    - assets/pages/images/vector-zZ7.png
    - assets/pages/images/menu-btn-user-tMX.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
